name: Build EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install

      - run: |
          cd frontend
          npm install
          npm run build

      - run: npx electron-builder --win

      - uses: actions/upload-artifact@v3
        with:
          name: app
          path: dist/*.exe