name: Build EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install root dependencies (Electron)
      - name: Install root deps
        run: npm install

      # Install and build frontend
      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build

      # Build Electron app
      - name: Build EXE
        run: npx electron-builder --win

      # Upload EXE file
      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: accounting-app
          path: dist/*.exe